
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Write a function that takes as input 4 numbers(diffmeans,sdev,samplesize, trials) and performs the following operations:
#Creates two normal populations of size 'samplesize' and standard deviation 'sdev'; one population has a mean of zero and the other has a mean of 'diffmeans' 
#Compares the two populations with a t.test and stores the p.value in a vector or dataframe
#Repeats this process in a loop 'trials' number of times
#Prints a histogram of pvalues with a red dotted line at 0.05 
#Prints the power of the test i.e the percentage of p.values <=0.05 (you may use this as the plot title instead of printing it)

t.power=function(diffmeans,sdev,samplesize,trials){
  results=data.frame(pvalue=as.numeric())
  
  for (i in 1:trials){
    pop_1=rnorm(samplesize,mean = 0,sd=sdev)
    pop_2=rnorm(samplesize,mean = diffmeans,sd=sdev)
    test=t.test(pop_1,pop_2)
    results[i,"pvalue"]=test$p.value
  }
  power=sum(results$pvalue<=0.05)/trials
  #ggplot(results,aes(x=pvalue))+geom_histogram()+geom_vline(xintercept = 0.05, color = "red", linetype = 'dotted', size=1)+
  #ggtitle(paste("Power:", power))  
  #If not using ggplot
  hist(results$pvalue,main = paste("Power:", power),breaks = trials/50)
  abline(v=0.05,lty="dashed",col="red")
}

```

```{r}
#Test the function with diffmeans=1, sd=1, sample size=10 and trials=1000 
t.power(diffmeans = 1,sdev = 1,samplesize = 10,trials = 1000)

#Vary diffmeans,sdev and samplesize one at a time to see their impact on power 
t.power(diffmeans = 1,sdev = 1,samplesize = 20,trials = 1000)  #doubled sample size to 20
t.power(diffmeans = 2,sdev = 1,samplesize = 10,trials = 1000)  #doubled diffmeans to 2
t.power(diffmeans = 1,sdev = 2,samplesize = 10,trials = 1000)  #doubled sdev to 2

#You can compare your results with the r function 'power.t.test' to see if they give similar results
power.t.test(n=10,delta = 1,sd = 1,sig.level = 0.05,type = "t",alternative = "t")
```

```{r}
#Modify the function so instead of printing the histogram it just returns the power 

t.power=function(diffmeans,sdev,samplesize,trials){
  results=data.frame(pvalue=as.numeric())
  
  for (i in 1:trials){
    pop_1=rnorm(samplesize,mean = 0,sd=sdev)
    pop_2=rnorm(samplesize,mean = diffmeans,sd=sdev)
    test=t.test(pop_1,pop_2)
    results[i,"pvalue"]=test$p.value
  }
  power=sum(results$pvalue<=0.05)/trials
  return(power)

  }

```

```{r}
#We want to analyze the effect of a range of sample sizes and mean differences on power (assuming sdev=1 and trial=1000). These values are given below:
diffs=c(0.25,0.5,0.75,1,2)
sizes=c(10,20,30,50,100)

#Write a loop that inputs these values to the function one by one and stores the output power for each combination in a dataframe. The output dataframe should look like a table with the different sample sizes as rows and different diffmeans as columns. 

res=data.frame()
for (i in 1:length(sizes)){
  for (j in 1:length(diffs)){
res[i,j]=t.power(samplesize=sizes[i],diffmeans=diffs[j],trials = 1000,sdev = 1 )  
  
  }  
}

colnames(res)=diffs
rownames(res)=sizes
res

```


```{r}
#Plot the power on the y-axis and sample size on the x-axis for each mean difference (on the same plot)
library(ggplot2)
library(reshape2)
res_m=res
res_m$Sample_Size=rownames(res)
res_m=melt(res_m,id.vars = "Sample_Size",variable.name = "Mean_Difference",value.name = "Power")
res_m$Sample_Size=as.numeric(res_m$Sample_Size)

ggplot(data=res_m,aes(x=Sample_Size,y=Power,col=Mean_Difference))+geom_line()

```