---
title: 'Homework 10: Hypothesis Testing'
author: "John Arbuthnot [YOUR NAME HERE]"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document: default
  pdf_document: default
subtitle: XDASI Fall 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)
library(mosaic)
```

## COVID-19 cases in NYC

"NYC_covid_cases_by_age.csv" contains weekly data of cases in NYC over the course of the pandemic. 

<!-- ======================================================================= -->
### 1) Import, tidy, and plot the data

#### a) Convert to long format

Read in the data file and convert the data to long format (you will need this in order to make the plot below).

  + You should preserve the `week_ending` column.
  + Get rid of the `age_all_ages` column.
  + Convert the rest of the columns to two new columns containing the `age_group` and `cases` information.
  + Turn the `age_groups` column into a factor (watch out, R likes to put everything in alphabetical order! you can set the levels in the correct order of age group by making a vector of the column names from the original data table and then selecting just columns 3:12)
  + Make sure the `week_ending` column is properly formatted as a Date type.
  
#### b) Percentage of cases in each age group

As a convenience for questions to come, also add a column containing the percentage of cases observed in each age group out of the total cases per week

Hint: dplyr will be really useful for this. It's a good idea to drop rows with `NA` at this point (look up `drop_na`).

#### c) Plot cases over time by age group

Create a plot that shows the trajectory of cases over the course of the pandemic broken down by age group.

<!-- ======================================================================= -->
### 2) First and second waves

The plot above shows that the number of cases over time forms "waves". Did the first and the second wave have a similar number of weekly recorded cases in all age groups?

#### a) Total cases in each wave

Subset the data that corresponds to the first wave. You have to decide for yourself where to draw the cutoffs on the time axis. Make a new data frame containing the total weekly number of cases in the first wave (sum them up across all age groups).

Then, do the same for the second wave.

#### b) Exploratory analysis

Explore the weekly number of cases for the two waves visually using a boxplot, histograms, and qq plots, and perform a test for normality.

#### c) Data transformations

If the data look highly skewed, it might be useful to transform the data. Try some different transformations and see if they help make the data look more normal.

Did any of the transformations you tried help at all? Discuss.

#### d) Statistical test

Run an appropriate statistical test to compare the number of cases in the first and second wave. Which wave was bigger?


<!-- ======================================================================= -->
### 3) Changes in case rates over time

We cannot directly compare the number of cases in each age category because we do not know the total number of population in each group (e.g. are there more cases among 75+ year olds than among 0-4 year olds because they get sick more or because there are more of them to begin with?) 

But we can look whether the **proportion** of cases that fall within each age group (out of the total number of weekly cases summed up across all age groups) differs with time. 

For example, is there a significant difference between the proportion of infections among younger adults vs. older adults in the first and second waves? What about before and after the appearance of the Delta variant?

#### a) Younger vs. older adults in waves 1 and 2

Did the age distribution of cases differ between the first two big waves of cases?

First, subset the data to get the percentage of cases in adults under 35 in each wave. Make a box plot to compare them and perform an appropriate statistical test for significance between the rates in the two waves. Then, do the same thing for adults 65 and up.

How did the rates of infection in these two groups differ between the first and second waves? Can you speculate on the reason for any observed differences?

#### b) Bootstrap confidence intervals

Perform a bootstrap analysis to get estimates for the median and 95% confidence intervals for young adults and older adults in each of the two waves.


<!-- ======================================================================= -->
### 4) Delta strain

The Delta strain became prevalent - i.e. started accounting for >50% all cases - on 6/23/21. Is there a significant difference between the proportion of infections among 25-34 year-olds before and after the rise of the Delta strain? 

#### a) Before and after Delta

Extract the data for the 25-34 age group from your long table and add a column that labels the data for each week as "Before_Delta" or "After_Delta" based on the date of appearance of the Delta variant.

#### b) Violin plot

Make a violin plot of the percentage of cases observed per week in the 25-34-year old group before and after the appearance of the Delta variant.

#### c) Permutation test

Perform a permutation ("shuffle") test for the observed median difference in the percentage of total cases in the 25-34 year-old age group before and after Delta. 

What's the $p$-value you get from the shuffle test? Compare this with with the result of another appropriate statistical test.

<!-- ======================================================================= -->
### 5) Breakthrough cases

Consider the following data of the number of NYC documented Covid cases, hospitalizations, and deaths among vaccinated and unvaccinated individuals:

+ Cases:
  + Vaccinated: 820
  + Unvaccinated: 4140  

+ Hospitalizations:
  + Vaccinated: 32
  + Unvaccinated: 349

+ Deaths:
  + Vaccinated: 4
  + Unvaccinated: 39

What is an appropriate test you could use to analyze these data? Explain.

Use this data to create a contingency table, and then perform the appropriate test to determine whether there is a significant difference between the vaccinated and unvaccinated groups.


<!-- THE END! :) =========================================================== -->
