---
title: "Week 4 Recitation"
author: "Chris"
date: "9/25/2019"
output: html_document
---

```{r setup, include=FALSE}
# Do not change any options in this setup block

knitr::opts_chunk$set(echo = TRUE, error=TRUE)

# Import libraries
require(ggplot2)
require(gganimate)
require(reshape2)
```


# Distributions

#### Poisson

```{r}

poisson.data <- NULL
for (i in 0:100) {
  lambda.num <- i / 2
  poisson.data <- rbind(poisson.data, data.frame(lambda = lambda.num, 
                                                 X = 0:50, 
                                                 PMF = dpois(0:50, lambda.num), 
                                                 CDF = ppois(0:50, lambda.num)))
}

ggplot(poisson.data, aes(x=X)) +
  geom_line(aes(y=PMF), color="red") +
  geom_line(aes(y=CDF), color="black") +
  theme_classic() +
  scale_x_discrete(limits=0:50) +
  coord_cartesian(ylim=c(0, 1)) +
  labs(title = 'Poisson Distribution [lambda = {round(frame_time, 2)}]', x = 'Number of Occurances of EVENT', y = 'Probability') +
  theme(axis.text.x = element_text(angle=90, hjust=0.5, vjust=1), title = element_text(face='bold', size = 14, hjust=0.5)) +
  transition_time(lambda)
```

#### Hypergeometric Distribution

```{r}

hyper.data <- NULL
for (i in 0:50) {
  pos.event <- 20
  neg.event <- 30
  hyper.data <- rbind(hyper.data, data.frame(n_sampled = i, 
                                             X = 0:50, 
                                             PMF = dhyper(0:50, pos.event, neg.event, i), 
                                             CDF = phyper(0:50, pos.event, neg.event, i)))
}

ggplot(hyper.data, aes(x=X)) +
  geom_line(aes(y=PMF), color="red") +
  geom_line(aes(y=CDF), color="black") +
  theme_classic() +
  scale_x_discrete(limits=0:50) +
  coord_cartesian(ylim=c(0, 1)) +
  labs(title = 'Hypergeometric Distribution [20 EVENTs / 50 TOTAL]', x = 'Number of Occurances of EVENT In {frame_time} Samples Taken', y = 'Probability') +
  theme(axis.text.x = element_text(angle=90, hjust=0.5, vjust=1), title = element_text(face='bold', size = 14, vjust=0.5, hjust=0.5)) +
  transition_time(n_sampled)
```

#### Negative Binomial Distribution

```{r}

nbinom.data <- NULL
for (i in 0:100) {
  p <- i / 100
  nbinom.data <- rbind(nbinom.data, data.frame(P = p, 
                                               X = 0:50, 
                                               PMF = dnbinom(0:50, 5, p), 
                                               CDF = pnbinom(0:50, 5, p)))
}

ggplot(nbinom.data, aes(x=X)) +
  geom_line(aes(y=PMF), color="red") +
  geom_line(aes(y=CDF), color="black") +
  theme_classic() +
  scale_x_discrete(limits=0:50) +
  coord_cartesian(ylim=c(0, 1)) +
  labs(title = 'Negative Binomial Distribution [p = {round(frame_time, 2)}]', x = 'Number of Failures Before 5 Successes (Success with probability p)', y = 'Probability') +
  theme(axis.text.x = element_text(angle=90, hjust=0.5, vjust=1), title = element_text(face='bold', size = 14, vjust=0.5, hjust=0.5)) +
  transition_time(P)
```

