
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Write a function that takes as input 4 numbers(diffmeans,sdev,samplesize, trials) and performs the following operations:
#Creates two normal populations of size 'samplesize' and standard deviation 'sdev'; one population has a mean of zero and the other has a mean of 'diffmeans' 
#Compares the two populations with a t.test and stores the p.value in a vector or dataframe
#Repeats this process in a loop 'trials' number of times
#Prints a histogram of pvalues with a red dotted line at 0.05 
#Prints the power of the test i.e the proportion of p.values <=0.05 (you may use this as the plot title instead of printing it)


```



```{r}
#Test the function with diffmeans=1, sd=1, sample size=10 and trials=1000 


#Vary diffmeans,sdev and samplesize one at a time to see their impact on power 


#You can compare your results with the r function 'power.t.test' to see if they give similar results

```


```{r}
#Modify the function so instead of printing the histogram it just returns the power 


```


```{r}
#We want to analyze the effect of a range of sample sizes and mean differences on power (assuming sdev=1 and trial=1000). These values are given below:
diffs=c(0.25,0.5,0.75,1,2)
sizes=c(10,20,30,50,100)

#Write a loop that inputs these values to the function one by one and stores the output power for each combination in a dataframe. The output dataframe should look like a table with the different sample sizes as rows and different diffmeans as columns. 



```


```{r}
#Plot the power on the y-axis and sample size on the x-axis for each mean difference (on the same plot)


```