title: "XDAS 2021"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil
search_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
